Add "Configure and link your App Clips"
Blackjacx/WWDC pull request #47
Opened 2020-06-24 21:15 UTC by rogerluan

This PR adds "Configure and link your app clips"

**Link:** https://developer.apple.com/videos/play/wwdc2020/10146/
**Presenters:** _Ada Chan, Luming Yin_
**Duration:** 22:56

Question: should we add the duration of every video on the top of the section? I find it useful, but it'd require everyone to do the same. Open to suggestions.

2020-06-24 21:15 UTC, rogerluan commented on README.md
> +   Duration: 22:56
Should we add this to every video? Thoughts?

2020-06-25 08:07 UTC, Blackjacx commented on README.md
> +   Duration: 22:56
I updated the contribution rules: https://github.com/Blackjacx/WWDC/blob/master/CONTRIBUTING.md#submitting-changes

2020-06-25 08:16 UTC, Blackjacx requested changes
Thanks for your input, really cool addition 🙏

2020-06-25 08:16 UTC, Blackjacx commented on README.md
> +Duration: 22:56
Please without the duration, see the new https://github.com/Blackjacx/WWDC/blob/master/CONTRIBUTING.md

2020-06-25 08:16 UTC, Blackjacx commented on README.md
> +https://developer.apple.com/videos/play/wwdc2020/10146/
If possible please use the short url version, it is easier to parse later on for me :-) You can just copy & paste one of the others and change the session number.

2020-06-25 13:22 UTC, rogerluan commented on README.md
> +   Duration: 22:56
Sweet, that works for me! 💪

2020-06-25 13:28 UTC, rogerluan commented
Sorry for putting all the fixes in a single merge commit 🤦 but I addressed your comments, fixed some typos in the new latest and removed redundant trailing whitespaces at the end of the file. :)

2020-06-25 14:15 UTC, Blackjacx approved these changes
All good bro, you are my lifesaver! Thanks for all the corrections. This is really nice and keeps up the quality of the notes 👍

2020-06-25 14:16 UTC, merged