Adding notes from two sessions
Blackjacx/WWDC pull request #51
Opened 2020-06-26 12:54 UTC by speedoholic

- Explore App Clips
- Meet the new photos picker

2020-06-26 18:18 UTC, rogerluan requested changes
Explore app clips was next on my list, glad you beat me to it (and I saw your PR before starting 😂 )

Two notes about my review:
- Although they look like too many comments, they're mostly just styling comments. You can apply all my suggestions with a single button directly from GitHub website 👍 
- The content is great! 🚀 

Thanks for the submission 💪

2020-06-26 18:18 UTC, rogerluan commented on README.md
> +        - Name and bundle ID for app clip added
```suggestion
        - Name and bundle ID for App Clip added
```

2020-06-26 18:18 UTC, rogerluan commented on README.md
> +            - Use #if !APPCLIP to compile out unwanted references in swift code
```suggestion
            - Use #if !APPCLIP to compile out unwanted references in Swift code
```

2020-06-26 18:18 UTC, rogerluan commented on README.md
> +    - Write code for AppClip
```suggestion
    - Write code for App Clip
```

2020-06-26 18:18 UTC, rogerluan commented on README.md
> +        - Include existing views in the AppClip’s content view
```suggestion
        - Include existing views in the App Clip’s content view
```

2020-06-26 18:18 UTC, rogerluan commented on README.md
> +    - AppClips are built using same UI components as an App
```suggestion
    - App Clips are built using same UI components as an app
```

2020-06-26 18:18 UTC, rogerluan commented on README.md
> +    - Unlike extensions, AppClip can make use of all iOS SDK APIs
```suggestion
    - Unlike extensions, App Clip can make use of all iOS SDK APIs
```

2020-06-26 18:18 UTC, rogerluan commented on README.md
> +    - New API for migrating data from AppClip to main app using shared data container once installed
```suggestion
    - New API for migrating data from App Clip to main app using shared data container once installed
```

2020-06-26 18:18 UTC, rogerluan commented on README.md
> +    - AppClip and it’s local storage will be deleted after period of inactivity
```suggestion
    - App Clip and its local storage will be deleted after period of inactivity
```

2020-06-26 18:18 UTC, rogerluan commented on README.md
> +    - Can not be launched via Universal links or custom URL schemes
```suggestion
    - Can not be launched via Universal Links or custom URL schemes
```

2020-06-26 18:18 UTC, rogerluan commented on README.md
> +    - iOS locates, downloads and runs the app clip
```suggestion
    - iOS locates, downloads and runs the App Clip
```

2020-06-26 18:18 UTC, rogerluan commented on README.md
> +    - If the app clip is not revisited for a while, the app clip and it’s data gets deleted
```suggestion
    - If the App Clip is not revisited for a while, the App Clip and its data gets deleted
```

2020-06-26 18:18 UTC, rogerluan commented on README.md
> +        - Treat app clip data as cache; which can be deleted
```suggestion
        - Treat App Clip data as cache; which can be deleted
```

2020-06-26 18:18 UTC, rogerluan commented on README.md
> +    - If the app clip is visited frequently, the app clip lifetime will be extended and data may never be cleared
```suggestion
    - If the App Clip is visited frequently, its lifespan will be extended and data may never be cleared
```

2020-06-26 18:18 UTC, rogerluan commented on README.md
> +        - When user downloads your app, iOS will automatically migrate the data container and the user permissions granted by user already
```suggestion
        - When user downloads your app, iOS will automatically migrate the data container and the permissions that were already granted by the user
```

2020-06-26 18:18 UTC, rogerluan commented on README.md
> +        - iOS still deletes the app clip and it’s container after copying the data container to the app
```suggestion
        - iOS still deletes the App Clip and its container after copying the data container to the app
```

2020-06-26 18:18 UTC, rogerluan commented on README.md
> +    - `SKOverlay` / AppStoreOverlayModifier (Refer to what’s new in In-app purchase session)
```suggestion
    - `SKOverlay` / `AppStoreOverlayModifier` (refer to [What’s new with in-app purchase](https://developer.apple.com/wwdc20/10661/) session)
```

2020-06-26 18:18 UTC, rogerluan commented on README.md
> +https://developer.apple.com/videos/play/wwdc2020/10652/
Please refer to the [Contributing.md](https://github.com/Blackjacx/WWDC/blob/master/CONTRIBUTING.md#submitting-changes) file 😃 
```suggestion
https://developer.apple.com/wwdc20/10652/
```

2020-06-26 18:18 UTC, rogerluan commented on README.md
> +## Meet the new Photos Picker
```suggestion
## Meet the new Photos picker
```

☝️ consistent with the WWDC website

2020-06-26 18:18 UTC, rogerluan commented on README.md
> +		- Only what user selects is passed back to the app
This is awesome!! 🤩 finally!

2020-06-26 18:18 UTC, rogerluan commented on README.md
> +  - `PHPickerConfiguration` which can include type filters is passed to `PHPickerViewController` which has delegates to handle responses
```suggestion
  - `PHPickerConfiguration` (which can include type filters) is passed to `PHPickerViewController`, which has delegates to handle responses
```

2020-06-26 18:18 UTC, rogerluan commented on README.md
> +  - `UIImagePickerController` is to be deprecated and replaced with `PHPickerViewController`
Great! This is good to know 🚀

2020-06-26 18:18 UTC, rogerluan commented on README.md
> +    - Surfaced through user actions via NFC / QR codes / Links in safari or other apps / Apple App Clip codes combine the ease of NFC and visual codes so they can be tapped or scanned
```suggestion
    - Surfaced through user actions via NFC / QR codes / links in safari or other apps / Apple App Clip codes combine the ease of NFC and visual codes so they can be tapped or scanned
```

2020-06-26 18:18 UTC, rogerluan commented on README.md
> +    - App Clip Experience URL is required to run App Clips which are parts of your App
```suggestion
    - App Clip Experience URL is required to run App Clips which are parts of your app
```

2020-06-29 08:35 UTC, Blackjacx commented
> Although they look like too many comments, they're mostly just styling comments. You can apply all my suggestions with a single button directly from GitHub website 👍

@rogerluan I applied all your changes one by one. Now I understand why you suggested the spell check editor 👍 MAy I ask which one you prefer?

> Explore app clips was next on my list, glad you beat me to it (and I saw your PR before starting 😂 )

I added a hint to the CONTRIBUTING.md to look at the open PR's if a session has already been processed.

2020-06-29 08:44 UTC, Blackjacx requested changes
As @rogerluan said, really great content 👍 I just found some minor typos. Thank you so much 🙏

2020-06-29 08:44 UTC, Blackjacx commented on README.md
> +    - Registered using App Store connect
```suggestion
    - Registered using App Store Connect
```

2020-06-29 08:44 UTC, Blackjacx commented on README.md
> +    - Surfaced through user actions via NFC / QR codes / links in safari or other apps / Apple App Clip codes combine the ease of NFC and visual codes so they can be tapped or scanned
```suggestion
    - Surfaced through user actions via NFC / QR codes / links in Safari or other apps / Apple App Clip codes combine the ease of NFC and visual codes so they can be tapped or scanned
```

2020-06-29 08:44 UTC, Blackjacx commented on README.md
> +            - Let go of unwanted swift files like navigation
```suggestion
            - Let go of unwanted Swift files like navigation
```

2020-06-29 08:45 UTC, merged

2020-06-29 08:50 UTC, rogerluan commented
> @rogerluan I applied all your changes one by one. 

Oh boy 😱 when the "git diff" suggestions are still there, you can click on "Files" (top of this page), and click the "Add suggestion to batch" (or something like this). Do this to every suggestion you wanna apply, then hit "apply" on the top of the page so you have 1 commit with all the suggestions applied at once :) it's a lot faster specially because applying the commits 1 by one requires N full page loads hehe. I hope this helps next time 😉 

>Now I understand why you suggested the spell check editor 👍 MAy I ask which one you prefer?

I use https://atom.io with an add-on to format markdown docs 👍 it has built-in spell check already, but the markdown preview is a 3rd party plugin.

> I added a hint to the CONTRIBUTING.md to look at the open PR's if a session has already been processed.

Oh this is great! Nice addition! 🚀

2020-06-30 01:02 UTC, speedoholic commented
Thanks @rogerluan and @Blackjacx for your appreciation and help on this.