Add session "Embrace Swift type inference"
Blackjacx/WWDC pull request #55
Opened 2020-06-27 01:11 UTC by rogerluan

2020-06-29 08:21 UTC, Blackjacx requested changes
Thanks for the addition. I love it when it becomes even hard to follow up with the PRs ^^

2020-06-29 08:21 UTC, Blackjacx commented on README.md
> +## Embrace Swift type inference
You forgot the TOX entry for this one, could not happen anymore after I merge your prefill-sessions PR, which is awesome btw. 🎉

2020-06-29 08:21 UTC, Blackjacx commented on README.md
> +	- Hold `⌥ (Option) + ⇧ (Shift)` on an error breadcrumb and drag it to the right of the source editor, to open the source editor and the breadcrumbs details side by side
I wound that code-style text makes symbols very small, this is fixed by bold text :-) 

```suggestion
	- Hold **⌥** (Option) **+ ⇧** (Shift) on an error breadcrumb and drag it to the right of the source editor, to open the source editor and the breadcrumbs details side by side
```

2020-06-29 13:00 UTC, Blackjacx commented
Would be cool if you could rebase your PR and put the session in the correct position :)

2020-06-29 23:16 UTC, rogerluan commented
Done @Blackjacx 👍

2020-06-30 09:26 UTC, Blackjacx approved these changes
Thanks for also contributing the more technical ones 🙏

2020-06-30 09:26 UTC, merged