Added "Why is my app getting killed?"
Blackjacx/WWDC pull request #68
Opened 2020-07-04 10:34 UTC by atereshkov

## Checklist

- [x] I have read the [CONTRIBUTING.md](https://github.com/Blackjacx/WWDC/blob/master/CONTRIBUTING.md) file.
- [x] I have reviewed my own notes for typos, grammar and consistency (if you're submitting notes for a new session)

## Description
Why is my app getting killed?

2020-07-05 22:44 UTC, Blackjacx requested changes
Hey this is a very important topic. Thanks for watching. Aso in my must watch list now but thanks to you I can watch it quickly 🙏

I covered all the API with URLs. I think this is a valuable addition for al people reading this since some of the links contain extended further info. Hope you like it 😊

2020-07-05 22:44 UTC, Blackjacx commented on summaries/2020/10078.md
> +      - `MXCPUExceptionDiagnostic`
```suggestion
      - [MXCPUExceptionDiagnostic](https://developer.apple.com/documentation/metrickit/mxcpuexceptiondiagnostic)
```

2020-07-05 22:44 UTC, Blackjacx commented on summaries/2020/10078.md
> +    - Consider moving work into `BGProcessingTask`
```suggestion
    - Consider moving work into [BGProcessingTask](https://developer.apple.com/documentation/backgroundtasks/bgprocessingtask)
```

2020-07-05 22:44 UTC, Blackjacx commented on summaries/2020/10078.md
> +    - Report available via `MXCrashDiagnostic`
```suggestion
    - Report available via [MXCrashDiagnostic](https://developer.apple.com/documentation/metrickit/mxcrashdiagnostic)
```

2020-07-05 22:44 UTC, Blackjacx commented on summaries/2020/10078.md
> +    - `UIApplication.beginBackgroundTask(expirationHandler:)`
```suggestion
    - [UIApplication.beginBackgroundTask(expirationHandler:)](https://developer.apple.com/documentation/uikit/uiapplication/1623031-beginbackgroundtask)
```

2020-07-05 22:44 UTC, Blackjacx commented on summaries/2020/10078.md
> +    - `UIApplication.endBackgroundTask(_:)`
```suggestion
    - [UIApplication.endBackgroundTask(_:)`](https://developer.apple.com/documentation/uikit/uiapplication/1622970-endbackgroundtask)
```

2020-07-05 22:44 UTC, Blackjacx commented on summaries/2020/10078.md
> +    - Counts exposed via `MXBackgroundExitData`
```suggestion
    - Counts exposed via [MXBackgroundExitData](https://developer.apple.com/documentation/metrickit/mxbackgroundexitdata)
```

2020-07-05 22:44 UTC, Blackjacx commented on summaries/2020/10078.md
> +      - Use the named variant of the UIKit API (`beginBackgroundTask(withName:expirationHandler:)`)
```suggestion
      - Use the named variant of the UIKit API ([beginBackgroundTask(withName:expirationHandler:)](https://developer.apple.com/documentation/uikit/uiapplication/1623051-beginbackgroundtask))
```

2020-07-05 22:44 UTC, Blackjacx commented on summaries/2020/10078.md
> +      - Inspect `MXMetricPayload`
```suggestion
      - Inspect [MXMetricPayload](https://developer.apple.com/documentation/metrickit/mxmetricpayload)
```

2020-07-05 22:44 UTC, Blackjacx commented on summaries/2020/10078.md
> +    - Check `backgroundTimeRemaining`
```suggestion
    - Check [backgroundTimeRemaining](https://developer.apple.com/documentation/uikit/uiapplication/1623029-backgroundtimeremaining)
```

2020-07-05 22:44 UTC, Blackjacx commented on summaries/2020/10078.md
> +    - Avoid leaking `UIBackgroundTaskIdentifier`
```suggestion
    - Avoid leaking [UIBackgroundTaskIdentifier](https://developer.apple.com/documentation/uikit/uibackgroundtaskidentifier)
```

2020-07-05 22:44 UTC, Blackjacx commented on summaries/2020/10078.md
> +  - `MXBackgroundExitData` shows how often these terminations happen providing counts of each termination type
```suggestion
  - [MXBackgroundExitData](https://developer.apple.com/documentation/metrickit/mxbackgroundexitdata) shows how often these terminations happen providing counts of each termination type
```

2020-07-05 22:44 UTC, Blackjacx commented on summaries/2020/10078.md
> +    - `MXCrashDiagnostic`
```suggestion
    - [MXCrashDiagnostic](https://developer.apple.com/documentation/metrickit/mxcrashdiagnostic)
```

2020-07-05 22:44 UTC, Blackjacx commented on summaries/2020/10078.md
> +    - Check out [What's New in MetricKit]() to get detailed information
```suggestion
    - Check out [What's New in MetricKit](https://github.com/Blackjacx/WWDC#whats-new-in-metrickit) to get detailed information
```

2020-07-06 09:54 UTC, atereshkov commented
Thank you @Blackjacx, I just forgot to add links. Added all of them with back-ticks.

2020-07-06 10:40 UTC, Blackjacx approved these changes
Looks good 👍

2020-07-06 10:41 UTC, merged